database:
  # IP or DNS entry for MySQL instance
  address: "localhost"
  # Database that will be used
  database: "critterchat"
  # User who has full credentials to the above DB
  user: "critterchat"
  # Password of said user
  password: "critterchat"

# Instance-wide secret key for cookie signing. Change this to something long and random. If you
# change this on an existing instance all existing login sessions will be invalidated.
cookie_key: "you_should_type_something_long_and_random_here"

# Instance-wide pepper for hashing passwords. Change this to something long and random. If you
# chnage this on an existing instance, all existing accounts will need their password reset.
password_key: "you_should_also_change_this_to_something_long_and_random"

# The name of the instance.
name: "Critter Chat Instance"

attachments:
  # The URL prefix of the attachment store.
  prefix: "/attachments/"

  # The attachment system that is used for attachment storage.
  system: "local"

  # The local directory where attachments are stored, if the system is "local".
  directory: "/tmp"

  # The key that will be used when hashing attachment names to ensure they are not enumerable.
  attachment_key: "you_should_additionally_change_this_to_something_long_and_random"
