"""Create rooms tables.

Revision ID: 5108f4c01ff1
Revises: a989e936411c
Create Date: 2025-06-29 21:54:51.331125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5108f4c01ff1'
down_revision = 'a989e936411c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('occupant_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('profile')
    op.drop_table('occupant')
    op.drop_table('action')
    # ### end Alembic commands ###
