"""Add info panel setting to settings.

Revision ID: 11caab5cdaf5
Revises: eebf49ab19f9
Create Date: 2025-07-02 22:46:12.488216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11caab5cdaf5'
down_revision = 'eebf49ab19f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('info', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'info')
    # ### end Alembic commands ###
