"""Add preference column for combined messages.

Revision ID: 12ba98c5d86c
Revises: f45022ff7308
Create Date: 2026-01-08 02:03:50.594857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ba98c5d86c'
down_revision = 'f45022ff7308'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('combined_messages', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'combined_messages')
    # ### end Alembic commands ###
