"""Add seen column to invites for badging and notification purposes.

Revision ID: 16ac62ce384a
Revises: e9f73c76365c
Create Date: 2026-03-08 03:12:54.572618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ac62ce384a'
down_revision = 'e9f73c76365c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('seen', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'seen')
    # ### end Alembic commands ###
