"""Add settings table so we can persist last room setting.

Revision ID: 1acf5383e9ee
Revises: bc6585534462
Create Date: 2025-06-30 21:52:40.363750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acf5383e9ee'
down_revision = 'bc6585534462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_room', sa.Integer(), nullable=True)
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=True)
    op.drop_index(op.f('user_id'), table_name='profile')
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.drop_index(op.f('session'), table_name='session')
    op.create_index(op.f('ix_session_session'), 'session', ['session'], unique=True)
    op.drop_index(op.f('username'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('username'), 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_session_session'), table_name='session')
    op.create_index(op.f('session'), 'session', ['session'], unique=True)
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.create_index(op.f('user_id'), 'profile', ['user_id'], unique=True)
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
