"""Add an autojoin column to rooms.

Revision ID: 1f5c51185c0b
Revises: 2aadf149219f
Create Date: 2025-07-26 19:56:25.099861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5c51185c0b'
down_revision = '2aadf149219f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('autojoin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'autojoin')
    # ### end Alembic commands ###
