"""Add desktop and mobile size preferences.

Revision ID: 22a9ed2c5320
Revises: ee0216d28d58
Create Date: 2026-01-25 19:36:30.677341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a9ed2c5320'
down_revision = 'ee0216d28d58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('desktop_size', sa.String(length=10), nullable=True))
    op.add_column('preferences', sa.Column('mobile_size', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'mobile_size')
    op.drop_column('preferences', 'desktop_size')
    # ### end Alembic commands ###
