"""Add admin controls preference.

Revision ID: 277efc9c2b3a
Revises: 91dc4a4c5311
Create Date: 2026-02-09 03:12:08.686700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277efc9c2b3a'
down_revision = '91dc4a4c5311'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('admin_controls', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'admin_controls')
    # ### end Alembic commands ###
