"""Add revoked column to invites.

Revision ID: 27d2cac0e828
Revises: 3df479a63c45
Create Date: 2026-03-05 21:20:11.385204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d2cac0e828'
down_revision = '3df479a63c45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'revoked')
    # ### end Alembic commands ###
