"""Add topic to room table.

Revision ID: 2aadf149219f
Revises: 1c8e9ad3424a
Create Date: 2025-07-14 22:51:59.688266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aadf149219f'
down_revision = '1c8e9ad3424a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('topic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'topic')
    # ### end Alembic commands ###
