"""Add ignored column to invites.

Revision ID: 3df479a63c45
Revises: 79992518fd6f
Create Date: 2026-03-05 20:53:56.763013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df479a63c45'
down_revision = '79992518fd6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('ignored', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'ignored')
    # ### end Alembic commands ###
