"""Enforce unique occupancy in rooms.

Revision ID: 4b21845a41af
Revises: 11caab5cdaf5
Create Date: 2025-07-03 01:20:23.419899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b21845a41af'
down_revision = '11caab5cdaf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uidrid', 'occupant', ['user_id', 'room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uidrid', 'occupant', type_='unique')
    # ### end Alembic commands ###
