"""Add public boolean to rooms.

Revision ID: 4bc85c6d869a
Revises: b5a5148651ee
Create Date: 2025-06-30 22:41:33.326493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc85c6d869a'
down_revision = 'b5a5148651ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('public', sa.Boolean(), nullable=True))
    op.drop_index(op.f('name'), table_name='room')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('name'), 'room', ['name'], unique=True)
    op.drop_column('room', 'public')
    # ### end Alembic commands ###
