"""Add join table for actions to have attachments.

Revision ID: 500c994b5274
Revises: f025b2a719c9
Create Date: 2026-01-19 17:44:26.055267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500c994b5274'
down_revision = 'f025b2a719c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_id', 'attachment_id', name='action_id_attachment_id'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_action_attachment_action_id'), 'action_attachment', ['action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_attachment_action_id'), table_name='action_attachment')
    op.drop_table('action_attachment')
    # ### end Alembic commands ###
