"""Add primary keys where necessary, part 4.

Revision ID: 57aab7197527
Revises: d3a5d3177486
Create Date: 2025-06-30 22:01:51.264545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aab7197527'
down_revision = 'd3a5d3177486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('occupant', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('profile', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('room', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('session', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('settings', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'id')
    op.drop_column('settings', 'id')
    op.drop_column('session', 'id')
    op.drop_column('room', 'id')
    op.drop_column('profile', 'id')
    op.drop_column('occupant', 'id')
    op.drop_column('action', 'id')
    # ### end Alembic commands ###
