"""Add primary keys where necessary, part 2.

Revision ID: 57cb00e78c8d
Revises: 08469a133de7
Create Date: 2025-06-30 21:58:00.358116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cb00e78c8d'
down_revision = '08469a133de7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('session', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('settings', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'id')
    op.drop_column('session', 'id')
    op.drop_column('profile', 'id')
    # ### end Alembic commands ###
