"""Add mastodon account link table.

Revision ID: 5a9278cd91cb
Revises: cdc717c87537
Create Date: 2026-02-11 23:45:39.321766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9278cd91cb'
down_revision = 'cdc717c87537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastodon_account_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'username', name='instance_id_username'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_mastodon_account_link_instance_id'), 'mastodon_account_link', ['instance_id'], unique=False)
    op.create_index(op.f('ix_mastodon_account_link_user_id'), 'mastodon_account_link', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mastodon_account_link_user_id'), table_name='mastodon_account_link')
    op.drop_index(op.f('ix_mastodon_account_link_instance_id'), table_name='mastodon_account_link')
    op.drop_table('mastodon_account_link')
    # ### end Alembic commands ###
