"""Add muted column to occupant.

Revision ID: 63baf7463908
Revises: 277efc9c2b3a
Create Date: 2026-02-09 17:44:31.309977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63baf7463908'
down_revision = '277efc9c2b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupant', sa.Column('muted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupant', 'muted')
    # ### end Alembic commands ###
