"""Add add composite unique attribute so a user can only have one invite out at a time.

Revision ID: 79992518fd6f
Revises: d52aff2ba1b2
Create Date: 2026-03-05 17:43:36.160548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79992518fd6f'
down_revision = 'd52aff2ba1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ridiuid', 'invite', ['room_id', 'invited_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ridiuid', 'invite', type_='unique')
    # ### end Alembic commands ###
