"""Swap details column of actions to JSON explicitly.

Revision ID: 7a52452ae11a
Revises: 22a9ed2c5320
Create Date: 2026-01-28 23:37:20.950436

"""
import json
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a52452ae11a'
down_revision = '22a9ed2c5320'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # First, need to ensure that everything actually is JSON.
    conn = op.get_bind()

    # First, do the easy thing, update everything that's empty to just empty JSON.
    sql = "UPDATE action SET details = '{}' WHERE details IS NULL"
    conn.execute(text(sql), {})  # type: ignore

    sql = "UPDATE action SET details = '{}' WHERE details = ''"
    conn.execute(text(sql), {})  # type: ignore

    # Second, gotta grab all messages and convert them.
    sql = "SELECT id, details FROM action WHERE action = 'message'"
    cursor = conn.execute(text(sql), {})  # type: ignore

    for row in cursor.mappings():
        rowid = row['id']
        details = row['details']

        sql = "UPDATE action SET details = :details WHERE id = :id LIMIT 1"
        conn.execute(text(sql), {'id': rowid, 'details': json.dumps({'message': details})})  # type: ignore

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'details',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'details',
               existing_type=sa.JSON(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
