"""Add original filename column to attachment table.

Revision ID: 830865253fc0
Revises: 12ba98c5d86c
Create Date: 2026-01-11 02:12:34.949566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830865253fc0'
down_revision = '12ba98c5d86c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('original_filename', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'original_filename')
    # ### end Alembic commands ###
