"""Add update timestamp to profile table for future use in notifying clients.

Revision ID: 8340d5926a0e
Revises: b899a47b2c8b
Create Date: 2025-09-01 22:31:38.644873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8340d5926a0e'
down_revision = 'b899a47b2c8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'timestamp')
    # ### end Alembic commands ###
