"""Allow null occupant for specific actions.

Revision ID: 91dc4a4c5311
Revises: c5a6c94f03c5
Create Date: 2026-02-05 06:05:03.668421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91dc4a4c5311'
down_revision = 'c5a6c94f03c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'occupant_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'occupant_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
