"""Add icon attachment IDs to rooom tables.

Revision ID: a0d25229eff3
Revises: ea7cdcaf66e3
Create Date: 2025-07-03 22:55:51.452353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d25229eff3'
down_revision = 'ea7cdcaf66e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupant', sa.Column('icon', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('icon', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'icon')
    op.drop_column('profile', 'icon')
    op.drop_column('occupant', 'icon')
    # ### end Alembic commands ###
