"""Add mobile notifications flag to preferences.

Revision ID: a9bff4f2d0dc
Revises: 67d52e28e7c2
Create Date: 2025-09-06 15:08:31.853158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9bff4f2d0dc'
down_revision = '67d52e28e7c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('mobile_audio_notifs', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'mobile_audio_notifs')
    # ### end Alembic commands ###
