"""Add primary keys where necessary, part 6.

Revision ID: b5a5148651ee
Revises: d12debc76cc3
Create Date: 2025-06-30 22:06:36.389500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a5148651ee'
down_revision = 'd12debc76cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'id')
    # ### end Alembic commands ###
