"""Add column for low motion preference.

Revision ID: b7665bf5cad9
Revises: f5b377400bd7
Create Date: 2026-08-23 16:15:59.613573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7665bf5cad9'
down_revision = 'f5b377400bd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('low_motion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'low_motion')
    # ### end Alembic commands ###
