"""Add inactive column to mastodon instance table.

Revision ID: ba9fe41bcb02
Revises: 5a9278cd91cb
Create Date: 2026-02-12 18:42:01.108850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9fe41bcb02'
down_revision = '5a9278cd91cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mastodon_instance', sa.Column('inactive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mastodon_instance', 'inactive')
    # ### end Alembic commands ###
