"""Add room_id back to occupant table so we can figure out what rooms we're in.

Revision ID: bc6585534462
Revises: f10d03b1f7a1
Create Date: 2025-06-30 03:02:25.051005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6585534462'
down_revision = 'f10d03b1f7a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupant', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_occupant_room_id'), 'occupant', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupant_room_id'), table_name='occupant')
    op.drop_column('occupant', 'room_id')
    # ### end Alembic commands ###
