"""Add purpose column to room table.

Revision ID: c1b8aabe8e09
Revises: 7a52452ae11a
Create Date: 2026-02-01 17:54:01.235210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'c1b8aabe8e09'
down_revision = '7a52452ae11a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # First, need to ensure that everything actually is JSON.
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('purpose', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###

    # Now, need to read the public column and set the purpose column accordingly.
    sql = "SELECT id, public FROM room"
    cursor = conn.execute(text(sql), {})  # type: ignore

    for row in cursor.mappings():
        rowid = row['id']
        public = row['public']

        if public:
            # Definitely a room.
            sql = "UPDATE room SET purpose = 'room' WHERE id = :id LIMIT 1"
            conn.execute(text(sql), {'id': rowid})  # type: ignore
        else:
            # Since we never supported UX for creating group chats, all remaining
            # rooms are direct messages.
            sql = "UPDATE room SET purpose = 'dm' WHERE id = :id LIMIT 1"
            conn.execute(text(sql), {'id': rowid})  # type: ignore


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'purpose')
    # ### end Alembic commands ###
