"""Add a moderated column for rooms.

Revision ID: c5a6c94f03c5
Revises: f37029774754
Create Date: 2026-02-05 04:01:21.056065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a6c94f03c5'
down_revision = 'f37029774754'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('moderated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'moderated')
    # ### end Alembic commands ###
