"""Add a last action timestamp to rooms.

Revision ID: c6a912c91db5
Revises: 4b21845a41af
Create Date: 2025-07-03 19:18:46.289459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a912c91db5'
down_revision = '4b21845a41af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('last_action', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'last_action')
    # ### end Alembic commands ###
