"""Add mastodon instance table.

Revision ID: cdc717c87537
Revises: 63baf7463908
Create Date: 2026-02-11 04:16:21.676286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc717c87537'
down_revision = '63baf7463908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mastodon_instance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=256), nullable=False),
    sa.Column('client_secret', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_mastodon_instance_base_url'), 'mastodon_instance', ['base_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mastodon_instance_base_url'), table_name='mastodon_instance')
    op.drop_table('mastodon_instance')
    # ### end Alembic commands ###
