"""Add search and invite privacy preferences.

Revision ID: cecbef2e7b6d
Revises: 16ac62ce384a
Create Date: 2026-03-20 00:44:59.386404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecbef2e7b6d'
down_revision = '16ac62ce384a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('search_privacy', sa.String(length=10), nullable=True))
    op.add_column('preferences', sa.Column('invite_privacy', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'invite_privacy')
    op.drop_column('preferences', 'search_privacy')
    # ### end Alembic commands ###
