"""Add primary keys where necessary, part 5.

Revision ID: d12debc76cc3
Revises: 57aab7197527
Create Date: 2025-06-30 22:04:27.325723

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd12debc76cc3'
down_revision = '57aab7197527'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'id')
    op.drop_column('session', 'id')
    op.drop_column('settings', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('session', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('profile', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
