"""Add rooms on top preference to DB.

Revision ID: d24c0203fdde
Revises: a9bff4f2d0dc
Create Date: 2025-09-06 15:47:54.877493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24c0203fdde'
down_revision = 'a9bff4f2d0dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('rooms_on_top', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'rooms_on_top')
    # ### end Alembic commands ###
