"""Add primary keys where necessary, part 3.

Revision ID: d3a5d3177486
Revises: 57cb00e78c8d
Create Date: 2025-06-30 22:00:38.338448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3a5d3177486'
down_revision = '57cb00e78c8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'id')
    op.drop_column('occupant', 'id')
    op.drop_column('profile', 'id')
    op.drop_column('room', 'id')
    op.drop_column('session', 'id')
    op.drop_column('settings', 'id')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('settings', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('session', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('room', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('profile', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('occupant', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('action', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
