"""Add timestamp to settings so we can always choose the last modified one.

Revision ID: e24811744d60
Revises: bda9a36a91de
Create Date: 2025-08-03 18:36:53.011940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24811744d60'
down_revision = 'bda9a36a91de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'timestamp')
    # ### end Alembic commands ###
