"""Index timestamp column on invites.

Revision ID: e9f73c76365c
Revises: 27d2cac0e828
Create Date: 2026-03-05 22:02:41.658879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f73c76365c'
down_revision = '27d2cac0e828'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invite_timestamp'), 'invite', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invite_timestamp'), table_name='invite')
    # ### end Alembic commands ###
