"""Add metadata column to attachments.

Revision ID: ee0216d28d58
Revises: 19fd56bdf944
Create Date: 2026-01-24 01:32:38.307651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0216d28d58'
down_revision = '19fd56bdf944'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'metadata')
    # ### end Alembic commands ###
