"""Add inactive field to occupants so we can leave rooms.

Revision ID: eebf49ab19f9
Revises: 4bc85c6d869a
Create Date: 2025-07-02 22:14:34.215577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'eebf49ab19f9'
down_revision = '4bc85c6d869a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupant', sa.Column('inactive', sa.Boolean(), nullable=True))
    conn = op.get_bind()
    conn.execute(text("UPDATE occupant SET `inactive` = FALSE"))  # type: ignore
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupant', 'inactive')
    # ### end Alembic commands ###
