"""Shuffle some columns for chat history.

Revision ID: f10d03b1f7a1
Revises: 5108f4c01ff1
Create Date: 2025-06-30 02:59:00.738158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f10d03b1f7a1'
down_revision = '5108f4c01ff1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_action_room_id'), 'action', ['room_id'], unique=False)
    op.add_column('occupant', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.drop_column('occupant', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupant', sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('occupant', 'nickname')
    op.drop_index(op.f('ix_action_room_id'), table_name='action')
    op.drop_column('action', 'room_id')
    # ### end Alembic commands ###
