"""Add a moderator column for room occupants.

Revision ID: f37029774754
Revises: 80f5515bc89c
Create Date: 2026-02-05 02:37:15.025245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37029774754'
down_revision = '80f5515bc89c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupant', sa.Column('moderator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupant', 'moderator')
    # ### end Alembic commands ###
