"""Add a column for storing user's color scheme preference.

Revision ID: f45022ff7308
Revises: d24c0203fdde
Create Date: 2025-09-19 21:39:20.136637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45022ff7308'
down_revision = 'd24c0203fdde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('color_scheme', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'color_scheme')
    # ### end Alembic commands ###
