"""Add column for tabbable elements preference.

Revision ID: f5b377400bd7
Revises: cecbef2e7b6d
Create Date: 2026-05-31 01:43:34.443114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b377400bd7'
down_revision = 'cecbef2e7b6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('tabbable_chat_elements', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'tabbable_chat_elements')
    # ### end Alembic commands ###
