"""Add update timestamp column to user, index timestamps.

Revision ID: fca87bd8e96a
Revises: ba9fe41bcb02
Create Date: 2026-02-25 23:43:35.375004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca87bd8e96a'
down_revision = 'ba9fe41bcb02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_preferences_timestamp'), 'preferences', ['timestamp'], unique=False)
    op.create_index(op.f('ix_profile_timestamp'), 'profile', ['timestamp'], unique=False)
    op.create_index(op.f('ix_settings_timestamp'), 'settings', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_column('user', 'timestamp')
    op.drop_index(op.f('ix_settings_timestamp'), table_name='settings')
    op.drop_index(op.f('ix_profile_timestamp'), table_name='profile')
    op.drop_index(op.f('ix_preferences_timestamp'), table_name='preferences')
    # ### end Alembic commands ###
