const CHAT_SENT = 'CHAT_SENT';
const CHAT_RECEIVED = 'CHAT_RECEIVED';
const MESSAGE_SENT = 'MESSAGE_SENT';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const MENTIONED = 'MENTIONED';
const USER_JOINED = 'USER_JOINED';
const USER_LEFT = 'USER_LEFT';
const USER_REACTED = 'USER_REACTED';
const REACTION_RECEIVED = 'REACTION_RECEIVED';
const AUDIO_PREFS = [
    CHAT_SENT,
    CHAT_RECEIVED,
    MESSAGE_SENT,
    MESSAGE_RECEIVED,
    MENTIONED,
    USER_JOINED,
    USER_LEFT,
    USER_REACTED,
    REACTION_RECEIVED,
];

const ACTIVATED = 'ACTIVATED';
const WELCOMED = 'WELCOMED';
const ADMINISTRATOR = 'ADMINISTRATOR';
const PERMISSIONS = [ACTIVATED, WELCOMED, ADMINISTRATOR];

export {
    CHAT_SENT,
    CHAT_RECEIVED,
    MESSAGE_SENT,
    MESSAGE_RECEIVED,
    MENTIONED,
    USER_JOINED,
    USER_LEFT,
    USER_REACTED,
    REACTION_RECEIVED,
    AUDIO_PREFS,
    ACTIVATED,
    WELCOMED,
    ADMINISTRATOR,
    PERMISSIONS,
};
