const CHAT_SENT = 'CHAT_SENT';
const CHAT_RECEIVED = 'CHAT_RECEIVED';
const MESSAGE_SENT = 'MESSAGE_SENT';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const MENTIONED = 'MENTIONED';
const AUDIO_PREFS = [CHAT_SENT, CHAT_RECEIVED, MESSAGE_SENT, MESSAGE_RECEIVED, MENTIONED];

export { CHAT_SENT, CHAT_RECEIVED, MESSAGE_SENT, MESSAGE_RECEIVED, MENTIONED, AUDIO_PREFS };
